LCX/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (HomeView,
					SegmentosView)

urlpatterns = [
    url(r'^$', HomeView, name='home'),
    url(r'^segmentos/$', SegmentosView, name='segmentos'),
]

empresas/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView

from .views import (HomeView, 
                    EmpresaDetailView,
                    InformeView,
                    DebugView,
                    # DataGenerator, 
                    Filling__eeffView,
                    ClientView, 
                    TransferListView, 
                    TransferDetailView, 
                    TrasferCreateView, 
                    CommercialClientsRecommendationsView2,
                    CommercialProvidersRecommendationsView2,
                    CommercialClientsRecommendationsView,
                    CommercialProvidersRecommendationsView,
                    FinancialRiskRecommendationsView,
                    ClientRiskRecommendationsView,
                    ProviderRiskRecommendationsView,
                    ProviderView,
                    EmpresasCreate,
                    ProductosCreate,
                    EstadosCreate,
                    CirbeCreate,
                    TranfersCreate,
                    ContentBasedCreate,
                    RecommendationsCreate,
                    OpportunityClientsView,
                    OpportunityProviderView,
                    FAQView,
                    SearchView,
                    IntroView,
                    SwitchView,
                    SummaryView,
                    get_data_mekko,
                    FinancialRiskRecommendationsView2,
                    MarketRiskRecommendationsView)

urlpatterns = [
    
    
    url(r'^intro/$', IntroView, name='empresas_intro'),
    url(r'^summary/$', SummaryView, name='summary'),
    url(r'^recommendations/clients$', CommercialClientsRecommendationsView2, name='recommendations_clients2'),
    url(r'^recommendations/providers$', CommercialProvidersRecommendationsView2, name='recommendations_providers2'),
    url(r'^recommendations/financial$', FinancialRiskRecommendationsView2, name='recommendations_financial2'),
    url(r'^get_data_mekko/$', get_data_mekko, name='get_data_mekko'),
    url(r'^$', HomeView, name='empresas_home'),
    #url(r'^create/$', EmpresaDetailView, name='empresa_create'),
    url(r'^(?P<pk>\d+)/$', EmpresaDetailView, name='detail'),
    url(r'^(?P<pk>\d+)/switch/$', SwitchView, name='switch'),
    url(r'^empresas/client_opportunities/$', OpportunityClientsView, name='client_opportunities'),
    url(r'^empresas/provider_opportunities/$', OpportunityProviderView, name='provider_opportunities'),
    #url(r'^update/$', EmpresaDetailView, name='empresa_update'),
    #url(r'^delete/$', EmpresaDetailView, name='empresa_delete'),
    # url(r'^empresa/(?P<empresa_id>[0-9]+)/transfer_create/$', TrasferCreateView, name='transfer_create'),
    url(r'^faq/$', FAQView, name='faq'),
    
    url(r'^debug_recomendaciones/$', DebugView, name='debug'),
    url(r'^recomendaciones/$', InformeView, name='informe'),
    url(r'^search/$', SearchView, name='search'),
    url(r'^clients/$', ClientView, name='clients'),
    url(r'^providers/$', ProviderView, name='providers'),
    url(r'^recommendations/$', CommercialClientsRecommendationsView, name='recommendations'),
    url(r'^recommendations/providers/$', CommercialProvidersRecommendationsView, name='recommendations_providers'),
    url(r'^recommendations/risk/financial$', FinancialRiskRecommendationsView, name='recommendations_financial_risk'),
    url(r'^recommendations/risk/client$', ClientRiskRecommendationsView, name='recommendations_client_risk'),
    url(r'^recommendations/risk/market$', MarketRiskRecommendationsView, name='risk_market'),
    url(r'^recommendations/risk/provider$', ProviderRiskRecommendationsView, name='recommendations_provider_risk'),
    url(r'^transfers/$', TransferListView, name='transfer_list'),
    url(r'^transfers/(?P<transfer_id>[0-9]+)/$', TransferDetailView, name='transfer_detail'),

    url(r'^generatedata/$', TemplateView.as_view(template_name="empresas/dataset_generator.html"), name='generate_empreses'),
    url(r'^generatedata/empresas/$', EmpresasCreate, name='empresas_create'),
    url(r'^generatedata/content_based/$', ContentBasedCreate, name='content_based_create'),
    url(r'^generatedata/productos/$', ProductosCreate, name='productos_create'),
    url(r'^generatedata/estados/$', EstadosCreate, name='estados_create'),
    url(r'^generatedata/transfers/$', TranfersCreate, name='transfers_create'),
    url(r'^generatedata/recommendations/$', RecommendationsCreate, name='recommedations_create'),
    url(r'^generatedata/cirbe/$', CirbeCreate, name='cirbe_create'),
    url(r'^generatedata/eeff_fill/$', Filling__eeffView, name='cirbe_create'),
    
]

marketplace/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from empresas import views
from risk_cro import views
from business.views import LandingView, AppsView, TestView
from allauth.account.views import LoginView, SignupView

urlpatterns = [
    url(r'^$', LandingView.as_view(), name='landing'), #views.home
    url(r'^admin/', admin.site.urls),
    url(r'^test/$', TestView),
    url(r'^pillstore/', AppsView.as_view(), name='home'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^empresas/', include('empresas.urls', namespace='empresas')),
    url(r'^cro/', include('risk_cro.urls', namespace='risk_cro')),
    url(r'^recommender/', include('recommender.urls', namespace='recommender')),
    url(r'^lcx/', include('LCX.urls', namespace='lcx')),
    url(r'^bidloan/', include('bidloan.urls', namespace='bidloan')),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recommender/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (SearchView,
                    HomeView,
                    ClientView,
                    ProviderView,
                    EmpresaDetailView,
                    OpportunityClientsView,
                    OpportunityProviderView)
                    
urlpatterns = [
    url(r'^$', HomeView, name='home'),
    url(r'^search/$', SearchView, name='search'),
    url(r'^clients/$', ClientView, name='clients'),
    url(r'^(?P<pk>\d+)/$', EmpresaDetailView, name='detail'),
    url(r'^providers/$', ProviderView, name='providers'),
    url(r'^client_oportunities/$', OpportunityClientsView, name='client_opportunities'),
    url(r'^provider_oportunities/$', OpportunityProviderView, name='provider_opportunities'),
]

recommender/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.conf import settings
from django.contrib import messages
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.generic import View
from django.utils import timezone
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.core.urlresolvers import reverse
from empresas.models import Empresa, EstadosFinancieros, RecommendedClients, RecommendedProviders
import random
from .permissions import *
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import Prefetch

BANCO_PRESENTACION = 1

@login_required
def SearchView(request):
	if has_santander_permission(request.user):
		BANCO_PRESENTACION = 2
	elif has_sabadell_permission(request.user):
		BANCO_PRESENTACION = 1
	else:
		BANCO_PRESENTACION = 1
		
	if has_recommender_permission(request.user) or request.user.is_superuser:
		if request.user.is_staff or request.user.is_superuser:
			autofilter = dict()
			company = Empresa.objects.all()
			request.session['banco'] = BANCO_PRESENTACION
			request.session['journey'] = False
			request.session['summary'] = True
			request.session.modified = True
			for c in company:
				autofilter[c.name] = c.image

			context = {
				'autofilter': json.dumps(autofilter, cls=DjangoJSONEncoder),
				'buttons': False
			}
			return render(request, "recommender/search.html", context)
		else:
			try:
				del request.session['company']
				del request.session['recommended_clients_page']
				del request.session['summary']
				del request.session['banco']
			except:
				pass
			company_id = 990
			request.session['banco'] = BANCO_PRESENTACION
			request.session['company'] = company_id
			request.session['summary'] = True
			request.session['journey'] = False
			request.session.modified = True
			company = Empresa.objects.filter(pk=company_id)
			company = company.prefetch_related('estados_financieros','transfers')[0]
			return redirect("/recommender/", {'empresa': company, 'company': company})
	else:
		messages.warning(request, 'A pesar de tener un usuario activo, no tienes permiso para entrar en esta aplicación')
		return redirect("/pillstore/", {})

@login_required
def HomeView(request):
	if has_recommender_permission(request.user) or request.user.is_superuser:
		try:
			referrer = request.META['HTTP_REFERER']
			if request.GET and request.GET.get('company_name',None):
				name = request.GET['company_name']
				try:
					del request.session['company']
					del request.session['recommended_clients_page']
				except:
					pass
				try:
					got_it = Empresa.objects.filter(name=name).first()
					company = got_it.pk #1492 #randint(0, queryset.count() - 1) # # ## 865 865-1
				except:
					return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
				request.session['company'] = company
				request.session['summary'] = True
				request.session.modified = True
				company_id = request.session.get('company')
				company = Empresa.objects.filter(pk=company_id)
				company = company.prefetch_related('estados_financieros','transfers')[0]
				return render(request, "recommender/home.html", {'empresa': company, 'company': company})
			else:
				company_id = request.session.get('company')
				company = Empresa.objects.filter(pk=company_id)
				company = company.prefetch_related('estados_financieros','transfers')[0]
				return render(request, "recommender/home.html", {'empresa': company, 'company': company})
		except:
			company_id = request.session.get('company')
			company = Empresa.objects.filter(pk=company_id)
			company = company.prefetch_related('estados_financieros','transfers')[0]
			return render(request, "recommender/home.html", {'empresa': company, 'company': company})
	else:
		messages.warning(request, 'A pesar de tener un usuario activo, no tienes permiso para entrar en esta aplicación')
		return redirect("/pillstore/", {})

@login_required
def ClientView(request):

	try:
		referrer = request.META['HTTP_REFERER']
		if 'intro' in referrer or 'summary' in referrer:
			request.session['journey'] = False
	except:
		request.session['journey'] = False

	today = timezone.now().date()
	company_id = request.session.get('company')
	company = Empresa.objects.filter(pk=company_id)
	company = company.prefetch_related('recommended__clientes_recomendados','transfers',
	Prefetch(
        "estados_financieros",
        queryset=EstadosFinancieros.objects.filter(empresa=company),
        to_attr="ultimos_estados_financieros"
    ))[0]

	sector, region, min_bill, comment = request.GET.get("sector"), request.GET.get("region"), request.GET.get("min_bill"), request.GET.get("comment")

	if request.session.get('recommended_clients_page') is None:
		request.session['recommended_clients_page'] = 1
	else:
		request.session['recommended_clients_page'] = request.session.get('recommended_clients_page') + 1

	recommended_clients = company.get_recommended_clients_v2() #company.recommended.all()
	# recommended_clients = recommended_clients.filter(similarity__gt=0)

	if sector is not None or region is not None or min_bill is not None:
		recommended_clients = company.get_recommended_clients_v2()
		if region=="true" or sector!="": 
			if region=="true":
				recommended_clients = recommended_clients.exclude(
					territorial=company.territorial)
			else:
				recommended_clients = recommended_clients.filter(
					territorial=company.territorial)
			if sector != "":
				recommended_clients = recommended_clients.filter(
					cnae_2=sector)
			context = {
				"company": company, 
				"recommended_clients": recommended_clients[:50],
				"loading_times": request.session['recommended_clients_page'],
				'banco': request.session.get('banco')
			}
			return render(request, "recommender/cards_layout.html", context)
		else:
			recommended_clients = recommended_clients.exclude(name=company.name)
			context = {
				"company": company,
				"recommended_clients": recommended_clients[:50],
				"loading_times": request.session['recommended_clients_page'],
				'banco': request.session.get('banco')
			}
			return render(request, "recommender/cards_layout.html", context)

	if not recommended_clients.first().spec_similarity:
		maybe = 0
		random_init = random.uniform(0.9, 1)
		for i, client in enumerate(recommended_clients):
			if random.uniform(0, 1) > 0.5:
				maybe += 1
			client.spec_similarity = random_init-(maybe*0.01)
			client.save()

	context = {
		"company": company, 
		"title": "Recommended clients",
		"today": today,
		'recommended_clients': recommended_clients[:50],
		"loading_times": request.session['recommended_clients_page'],
		'journey': request.session.get('journey'),
		'banco': request.session.get('banco')
	}
	return render(request, "recommender/recommended_clients.html", context)

"""-------------------------------------------------------"""
"""				PROVIDERS VIEWS 							  """
"""-------------------------------------------------------"""

# @login_required
def ProviderView(request):

	try:
		referrer = request.META['HTTP_REFERER']
		if 'intro' in referrer or 'summary' in referrer:
			request.session['journey'] = False
	except:
		request.session['journey'] = False

	today = timezone.now().date()
	company_id = request.session.get('company')
	company = Empresa.objects.filter(pk=company_id)
	company = company.prefetch_related('providers_recommended__clientes_recomendados__estados_financieros','transfers')[0] #'estados_financieros','recommended','recommended__clientes_recomendados'

	recommended_providers = company.get_recommended_providers_v2() #company.providers_recommended.all()
	sector, region, min_bill, comment = request.GET.get("sector"), request.GET.get("region"), request.GET.get("min_bill"), request.GET.get("comment")

	if request.session.get('recommended_providers_page') is None:
		request.session['recommended_providers_page'] = 1
	else:
		request.session['recommended_providers_page'] = request.session.get('recommended_providers_page') + 1

	if sector is not None or region is not None or min_bill is not None:
		recommended_providers = company.get_recommended_providers_v2() #company.providers_recommended.all()
		if region=="true" or sector!="": 
			if region=="true":
				recommended_providers = company.recommended.filter(
					territorial=company.territorial)
			if sector!="":
				# cnae_2=sector, 
				recommended_providers = recommended_providers.filter(
					cnae_2=sector)
			context = {
				"company": company, 
				"recommended_providers": recommended_providers[:50],
				"loading_times": request.session['recommended_providers_page']
			}
			return render(request, "recommender/cards_layout.html", context)
		else:
			recommended_providers = company.recommended.all()
			context = {
				"company": company, 
				"recommended_providers": recommended_providers[:50],
				"loading_times": request.session['recommended_providers_page']
			}
			return render(request, "recommender/cards_layout.html", context)

	if not recommended_providers.first().spec_similarity:
		maybe = 0
		random_init = random.uniform(0.9, 1)
		for i, provider in enumerate(recommended_providers):
			if random.uniform(0, 1) > 0.5:
				maybe += 1
			provider.spec_similarity = random_init-(maybe*0.01)
			provider.save()

	context = {
		"company": company, 
		"title": "Recommended providers",
		"recommended_providers": recommended_providers[:50],
		"today": today,
		"loading_times": request.session['recommended_providers_page'],
		'journey': request.session.get('journey')
	}
	return render(request, "recommender/recommended_providers.html", context)


@login_required
def OpportunityClientsView(request):
	company_id = request.session.get('company')
	company = Empresa.objects.filter(pk=company_id).first()

templates/recommender/home.html
{% extends "app_base.html" %}
{% load static %}

{% block page_title %}
Marketplace B2B
{% endblock %}

{% block side-nav %}{% include "side-nav_market.html" %}{% endblock %}

{% block content %}

<img src="{% static 'images/pexels-photo-165263.jpeg' %}" id="bg" alt="">
  <div class="row" style="padding-bottom: 0px; padding-top: 25px;">

      <div class="col m7"></div>

      <div class="col m4">
        <div class="row">
          <div class="col s12 m12">
              <div class="card small hoverable" style="max-height: 250px;">
              <div class="card-image"  style="max-height: 100%;">
                <img src="{% static 'images/rsz_rocks.jpg' %}">
                <span class="card-title black-text" style="top: 0;">Clientes recomendados</span>
              </div>
              <div class="card-action">
                <a href="{% url 'recommender:clients' %}" class="grey-text text-darken-3">Marketplace de clientes</a>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col s12 m12">
              <div class="card small hoverable"  style="max-height: 250px;">
                <div class="card-image" style="max-height: 100%;">
                  <img src="{% static 'images/rsz_providers.jpg' %}">
                  <span class="card-title" style="top: 0;">Proveedores recomendados</span>
                </div>
                <div class="card-action ">
                  <a href="{% url 'recommender:providers' %}" class="grey-text text-darken-3">Marketplace de proveedores</a>
                </div>
              </div>
          </div>
        </div>

      </div>
  </div>
{% endblock %}

templates/recommender/search.html
{% extends "app_base.html" %}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% block page_title %}
Marketplace B2B
{% endblock %}

{% block body_class %}background_grey{% endblock %}

{% block content %}
<style type="text/css">
  /* label color */
   .input-field label {
     color: #ffffff;
     border-bottom: 0px solid #ffffff;
   }
   /* label focus color */
   .input-field input[type=text]:focus + label {
     color: #f6f9ff;
     border-bottom: 0px solid #ffffff;
   }
   /* label underline focus color */
   .input-field input[type=text]:focus {
     border-bottom: 1px solid #ffffff;
     box-shadow: 0 1px 0 0 #ffffff;
   }
   /* valid color */
   .input-field input[type=text].valid {
     border-bottom: 1px solid #000;
     box-shadow: 0 1px 0 0 #000;
   }
   /* invalid color */
   .input-field input[type=text].invalid {
     border-bottom: 1px solid #000;
     box-shadow: 0 1px 0 0 #000;
   }
   /* icon prefix focus color */
   .input-field .prefix.active {
     color: #ffffff;
   }
   /* icon prefix focus color */
   .input-field .prefix {
     color: #ffffff;
   }
</style>

{% include "navbar.html" %}

<div class="row" style="padding-top: 10rem;">
  <div class="col s12 m3"></div>
  <div class="col s12 m6">
    <!-- <div class="card-panel grey "> -->
        <div class="row">
          <div class="col m12 s12">
            <h3 class="light grey-text center-align">Nuevos compañeros de viaje</h3>
            <div class="row padding_title">
              <div class="col m12 s12" style="padding-top: 3rem;">
                <form action="{% url 'recommender:home' %}" method="get" id="search_company">
                  {% csrf_token %}
                  <div class="input-field col s12" >
                    <i class="material-icons prefix">search</i>
                    <input type="text" id="autocomplete-input-search" name="company_name" class="autocomplete_search">
                    <label for="autocomplete-input-search">Buscar recomendaciones para la empresa...</label>
                  </div>
                </form>
              </div>
            </div>
          </div>
          
      </div>
    <!-- </div> -->
  </div>
  <div class="col s12 m3"></div>
</div>


<img src="{% static 'images/pexels-photo-143967.jpeg' %}" id="bg" alt="">

{% endblock %}

{% block alt_js %}
  <script type="text/javascript">
  (function($){
    $(function(){

      $('input.autocomplete_search').autocomplete({
        data: {{autofilter|safe}},
        limit: 5, // The max amount of results that can be shown at once. Default: Infinity.
      });

    $("input").keypress(function(event) {
      if (event.which == 13) {
          event.preventDefault();
          $("#search_company").submit();
      }
  });
    }); // end of document ready
  })(jQuery); // end of jQuery name space
  </script>
{% endblock alt_js %}

templates/recommender/side-nav_market.html
  {% load compress %}
  {% load static %}

  <ul id="slide-out" class="side-nav">
      <li>
        <div class="userView">
          <div class="background">
            <img src="{% static 'images/testimonial-bg.jpg' %}">
          </div>
          <a href="{% url 'recommender:detail' pk=company.pk %}"><img class="circle" src="{{ company.image }}"></a>
          <a href="{% url 'recommender:detail' pk=company.pk %}"><span class="white-text name">{{ company.name }}</span></a>
          <a href="{% url 'recommender:detail' pk=company.pk %}"><span class="white-text email">{{ company.email }}</span></a>
          <a href="{% url 'recommender:detail' pk=company.pk %}"><span class="white-text light email">Usuario: {{ request.user.get_full_name }}</span></a>
        </div>
      </li>
      <li><a href="{% url 'recommender:home' %}"><i class="material-icons">view_quilt</i>Home</a></li>
      <li><a href="{% url 'recommender:detail' pk=company.pk %}"><i class="material-icons">airplay</i>Mi perfil</a></li>
      <!-- <li><a href="{% url 'empresas:faq' %}"><i class="material-icons">info_outline</i>FAQ & Comentarios</a></li> -->
      <li><div class="divider"></div></li>
      <li><a class="subheader">Marketplace</a></li>
      <li><a href="{% url 'recommender:clients' %}"><i class="material-icons">person_pin</i>Nuevos clientes!</a></li>
      <li><a href="{% url 'recommender:providers' %}"><i class="material-icons">settings_input_antenna</i>Nuevos proveedores!</a></li>
      <li><div class="divider"></div></li>
      <li><a class="subheader">Seguimiento</a></li>
      <li><a href="{% url 'recommender:client_opportunities' %}"><i class="material-icons">person_pin</i>Clientes guardados</a></li>
      <li><a href="{% url 'recommender:provider_opportunities' %}"><i class="material-icons">settings_input_antenna</i>Proveedores guardados</a></li>
      <!-- <li><a href="{% url 'empresas:recommendations' %}"><i class="material-icons">assessment</i>Commercial monitoring</a></li>
      <li><a href="{% url 'empresas:recommendations_financial_risk' %}"><i class="material-icons">trending_down</i>Risk monitoring</a></li> -->
    
      <li><div class="divider"></div></li>
      <li><a class="subheader">Opciones</a></li>
      <!-- <li><a class="waves-effect" href="#!">Ajustes<i class="material-icons">lock_open</i></a></li> -->
      <li><a class="waves-effect" href="{% url 'empresas:search' %}">Salir<i class="material-icons">input</i></a></li>
    </ul>