LCX/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (HomeView,
					SegmentosView)

urlpatterns = [
    url(r'^$', HomeView, name='home'),
    url(r'^segmentos/$', SegmentosView, name='segmentos'),
]

empresas/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView

from .views import (HomeView, 
                    EmpresaDetailView,
                    InformeView,
                    DebugView,
                    # DataGenerator, 
                    Filling__eeffView,
                    ClientView, 
                    TransferListView, 
                    TransferDetailView, 
                    TrasferCreateView, 
                    CommercialClientsRecommendationsView2,
                    CommercialProvidersRecommendationsView2,
                    CommercialClientsRecommendationsView,
                    CommercialProvidersRecommendationsView,
                    FinancialRiskRecommendationsView,
                    ClientRiskRecommendationsView,
                    ProviderRiskRecommendationsView,
                    ProviderView,
                    EmpresasCreate,
                    ProductosCreate,
                    EstadosCreate,
                    CirbeCreate,
                    TranfersCreate,
                    ContentBasedCreate,
                    RecommendationsCreate,
                    OpportunityClientsView,
                    OpportunityProviderView,
                    FAQView,
                    SearchView,
                    IntroView,
                    SwitchView,
                    SummaryView,
                    get_data_mekko,
                    FinancialRiskRecommendationsView2,
                    MarketRiskRecommendationsView)

urlpatterns = [
    
    
    url(r'^intro/$', IntroView, name='empresas_intro'),
    url(r'^summary/$', SummaryView, name='summary'),
    url(r'^recommendations/clients$', CommercialClientsRecommendationsView2, name='recommendations_clients2'),
    url(r'^recommendations/providers$', CommercialProvidersRecommendationsView2, name='recommendations_providers2'),
    url(r'^recommendations/financial$', FinancialRiskRecommendationsView2, name='recommendations_financial2'),
    url(r'^get_data_mekko/$', get_data_mekko, name='get_data_mekko'),
    url(r'^$', HomeView, name='empresas_home'),
    #url(r'^create/$', EmpresaDetailView, name='empresa_create'),
    url(r'^(?P<pk>\d+)/$', EmpresaDetailView, name='detail'),
    url(r'^(?P<pk>\d+)/switch/$', SwitchView, name='switch'),
    url(r'^empresas/client_opportunities/$', OpportunityClientsView, name='client_opportunities'),
    url(r'^empresas/provider_opportunities/$', OpportunityProviderView, name='provider_opportunities'),
    #url(r'^update/$', EmpresaDetailView, name='empresa_update'),
    #url(r'^delete/$', EmpresaDetailView, name='empresa_delete'),
    # url(r'^empresa/(?P<empresa_id>[0-9]+)/transfer_create/$', TrasferCreateView, name='transfer_create'),
    url(r'^faq/$', FAQView, name='faq'),
    
    url(r'^debug_recomendaciones/$', DebugView, name='debug'),
    url(r'^recomendaciones/$', InformeView, name='informe'),
    url(r'^search/$', SearchView, name='search'),
    url(r'^clients/$', ClientView, name='clients'),
    url(r'^providers/$', ProviderView, name='providers'),
    url(r'^recommendations/$', CommercialClientsRecommendationsView, name='recommendations'),
    url(r'^recommendations/providers/$', CommercialProvidersRecommendationsView, name='recommendations_providers'),
    url(r'^recommendations/risk/financial$', FinancialRiskRecommendationsView, name='recommendations_financial_risk'),
    url(r'^recommendations/risk/client$', ClientRiskRecommendationsView, name='recommendations_client_risk'),
    url(r'^recommendations/risk/market$', MarketRiskRecommendationsView, name='risk_market'),
    url(r'^recommendations/risk/provider$', ProviderRiskRecommendationsView, name='recommendations_provider_risk'),
    url(r'^transfers/$', TransferListView, name='transfer_list'),
    url(r'^transfers/(?P<transfer_id>[0-9]+)/$', TransferDetailView, name='transfer_detail'),

    url(r'^generatedata/$', TemplateView.as_view(template_name="empresas/dataset_generator.html"), name='generate_empreses'),
    url(r'^generatedata/empresas/$', EmpresasCreate, name='empresas_create'),
    url(r'^generatedata/content_based/$', ContentBasedCreate, name='content_based_create'),
    url(r'^generatedata/productos/$', ProductosCreate, name='productos_create'),
    url(r'^generatedata/estados/$', EstadosCreate, name='estados_create'),
    url(r'^generatedata/transfers/$', TranfersCreate, name='transfers_create'),
    url(r'^generatedata/recommendations/$', RecommendationsCreate, name='recommedations_create'),
    url(r'^generatedata/cirbe/$', CirbeCreate, name='cirbe_create'),
    url(r'^generatedata/eeff_fill/$', Filling__eeffView, name='cirbe_create'),
    
]

marketplace/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from empresas import views
from risk_cro import views
from business.views import LandingView, AppsView, TestView
from allauth.account.views import LoginView, SignupView

urlpatterns = [
    url(r'^$', LandingView.as_view(), name='landing'), #views.home
    url(r'^admin/', admin.site.urls),
    url(r'^test/$', TestView),
    url(r'^pillstore/', AppsView.as_view(), name='home'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^empresas/', include('empresas.urls', namespace='empresas')),
    url(r'^cro/', include('risk_cro.urls', namespace='risk_cro')),
    url(r'^recommender/', include('recommender.urls', namespace='recommender')),
    url(r'^lcx/', include('LCX.urls', namespace='lcx')),
    url(r'^bidloan/', include('bidloan.urls', namespace='bidloan')),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

risk_cro/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (HomeView,
					CreditRaterView,
					RaterView,
                    EmpresaDetailView,
                    SearchView,
                    SummaryView,
                    MarketRiskRecommendationsView,
                    CommercialClientsRecommendationsView,
                    CommercialProvidersRecommendationsView,
                    FinancialRiskRecommendationsView)

urlpatterns = [
    url(r'^$', HomeView, name='cro_home'),
    url(r'^search/$', SearchView, name='search'),
    url(r'^summary/$', SummaryView, name='summary'),
    url(r'^(?P<pk>\d+)/$', EmpresaDetailView, name='detail'),
    url(r'^creditrater/$', CreditRaterView, name='credit_risk'),
    url(r'^rating/$', RaterView, name='rater'),
    url(r'^market_risk/$', MarketRiskRecommendationsView, name='market_risk'),
    url(r'^client_risk/$', CommercialClientsRecommendationsView, name='client_risk'),
    url(r'^provider_risk/$', CommercialProvidersRecommendationsView, name='provider_risk'),
    url(r'^financial_risk/$', FinancialRiskRecommendationsView, name='financial_risk'),
    
]

risk_cro/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
import numpy as np
import pandas as pd
from django.conf import settings
from django.db import models
from  django.core.urlresolvers import reverse
from django.conf import settings
from django.db.models import Avg, Max, Min, Count, Sum, F
from django.db.models.functions import TruncMonth
from django.db.models import Prefetch
from calendar import monthrange
from datetime import datetime, timedelta
from django.utils.timezone import utc
import random

# ------------------------------------------------------------------
# Model Rating
# Tabla y funciones del model Empresa
# ------------------------------------------------------------------

class Rating(models.Model):

    # --- Variables de modelo ---
    name = models.CharField(max_length=255)
    sector = models.CharField(max_length=255)
    antiguedad = models.CharField(max_length=255)
    fondos_propios = models.BigIntegerField()
    activo_corriente = models.BigIntegerField()
    activo_no_corriente = models.BigIntegerField()
    pasivo_corriente = models.BigIntegerField()
    pasivo_no_corriente = models.BigIntegerField()
    importe_neto_cifra_negocio = models.BigIntegerField()
    gastos_financieros = models.BigIntegerField()
    resultados_antes_impuestos = models.BigIntegerField()

    # --- Parametros del modelo ---
    link = settings.DATA_FOLDER+'sectorial.csv'
    sectorial_data = pd.read_csv(link, encoding='latin1', sep=';', decimal=',')
    link = settings.DATA_FOLDER+'sectores.csv'
    sectores_data = pd.read_csv(link, encoding='latin1', sep=';', decimal=',')
    m_activo_corriente = [1.010126, 0.6905959, 0.3511273, 0]
    m_ratio_autonomia_financiera = [0, 0.1646282, 0.6776536, 1.29607]
    m_gastos_financiera_entre_ventas = [0.9693287, 0.8044454, 0.3827373, 0]
    m_resultados_entre_ventas = [0, 0.2427986, 0.3750541, 0.6537845]
    m_grupo_sectorial = [0, 0.05615981, 0.4273994, 1.064419]
    m_independiente = -0.2205067
    tramos = None
    rating = None
    tramos_grafico = None

    # Seleccionar de la tabla de valores medios sectoriales los valores del sector
    def get_sector_params(self, sector):
        return self.sectores_data[self.sectores_data['SECTOR'] == sector]

    # Traducir mediante los percentiles el tramo en el que nos encontramos
    def get_tramo(self, input_data, data, var):
        tramo = 0
        for index, row in data.iterrows():
            tramo += 1
            if row[var]>input_data:
                return tramo
        return 4

    # Seleccionar el tramo como traducción del sector de actividad
    def tramo_grupo_sectorial(self):
        if self.get_sector_params(self.sector)['AGRUPACI_N'].values=="MUY BUENO":
            return 4
        elif self.get_sector_params(self.sector)['AGRUPACI_N'].values=="BUENO":
            return 3
        elif self.get_sector_params(self.sector)['AGRUPACI_N'].values=="REGULAR":
            return 2
        elif self.get_sector_params(self.sector)['AGRUPACI_N'].values=="MALO":
            return 1
        else:
            return "error"

    # Traducción del rating en palabras para dar diagnóstico final
    def traduccion_rating(self, rating):
        if self.importe_neto_cifra_negocio<=900000:
            if rating<1.1:
                return "SITUACIÓN SECTORIAL MEJORABLE"
            elif rating<2.58:
                return "SITUACIÓN SECTORIAL BUENA"
            else:
                return "SITUACIÓN SECTORIAL EXCELENTE"
        else:
            if rating<0.96:
                return "SITUACIÓN SECTORIAL MEJORABLE"
            elif rating<2.58:
                return "SITUACIÓN SECTORIAL BUENA"
            else:
                return "SITUACIÓN SECTORIAL EXCELENTE"

    # Motor de cálculo del rating
    def rate_it(self):
        # Selección de datos sectoriales
        datos_sectorial = self.sectorial_data[self.sectorial_data['COD_SEC20'].isin(self.get_sector_params(self.sector)['#'].values)]
        # Cálculo de los tramos del modelo
        tramo_activo_corriente = self.get_tramo(self.activo_corriente, datos_sectorial, 'Activo_Corriente')
        tramo_r_Autonomia_Financiera = self.get_tramo(float(self.fondos_propios) / float(self.pasivo_corriente + self.pasivo_no_corriente + self.fondos_propios), datos_sectorial, 'R_Autonomia_Financiera')
        tramo_gastos_fin_entre_ventas = self.get_tramo(float(self.gastos_financieros)/float(self.importe_neto_cifra_negocio), datos_sectorial, 'R_Gastos_Financieros')
        tramo_resultados_entre_ventas = self.get_tramo(float(self.resultados_antes_impuestos)/float(self.importe_neto_cifra_negocio), datos_sectorial, 'R_Resultados_Sobre_Ventas')
        tramo_grupo_sectorial = self.tramo_grupo_sectorial()
        self.tramos = [tramo_activo_corriente, tramo_r_Autonomia_Financiera, tramo_gastos_fin_entre_ventas, tramo_resultados_entre_ventas, tramo_grupo_sectorial]


        self.tramos_grafico = [tramo_r_Autonomia_Financiera, tramo_gastos_fin_entre_ventas, tramo_resultados_entre_ventas, tramo_grupo_sectorial]
        
        self.rating = self.m_activo_corriente[tramo_activo_corriente-1] + self.m_ratio_autonomia_financiera[tramo_r_Autonomia_Financiera-1] + self.m_gastos_financiera_entre_ventas[tramo_gastos_fin_entre_ventas-1] + self.m_resultados_entre_ventas[tramo_resultados_entre_ventas-1] + self.m_grupo_sectorial[tramo_grupo_sectorial-1] + self.m_independiente
        return [self.rating, self.traduccion_rating(self.rating)]

    def ratio_solvencia(self):
        if (self.pasivo_corriente + self.pasivo_no_corriente) > 0:
            return float(self.activo_corriente) / float(self.pasivo_corriente + self.pasivo_no_corriente)
        else:
            return 0

    def ratio_endeudamiento(self):
        if (self.fondos_propios) > 0:
            return float(self.pasivo_corriente + self.pasivo_no_corriente) / float(self.fondos_propios)
        else:
            return 0

    def ratio_endeudamiento_cp(self):
        if (self.fondos_propios) > 0:
            return float(self.pasivo_corriente) / float(self.fondos_propios)
        else:
            return 0

    def ratio_autonomia(self):
        if (self.pasivo_corriente + self.pasivo_no_corriente) > 0:
            return float(self.fondos_propios) / float(self.pasivo_corriente + self.pasivo_no_corriente)
        else:
            return 0

    def ratio_cobertura_inmovilizado_FFPP(self):
        if (self.activo_no_corriente) > 0:
            return float(self.fondos_propios) / float(self.activo_no_corriente)
        else:
            return 0

    def ratio_rentabilidad_economica(self):
        if (self.activo_corriente + self.activo_no_corriente) > 0:
            return float(self.resultados_antes_impuestos) / float(self.activo_corriente + self.activo_no_corriente)
        else:
            return 0

    def ratio_autonomia_financiera(self):
        if (self.pasivo_corriente + self.pasivo_no_corriente + self.fondos_propios) > 0:
            return float(self.fondos_propios) / float(self.pasivo_corriente + self.pasivo_no_corriente + self.fondos_propios)
        else:
            return 0

    def ratio_dependencia_financiera(self):
        if (self.pasivo_corriente + self.pasivo_no_corriente + self.fondos_propios) > 0:
            return 1 - (float(self.fondos_propios) / float(self.pasivo_corriente + self.pasivo_no_corriente + self.fondos_propios))
        else:
            return 0

    def ratio_gastos_financieros(self):
        if (self.importe_neto_cifra_negocio) > 0:
            return float(self.gastos_financieros) / float(self.importe_neto_cifra_negocio)
        else:
            return 0

    def ratio_rentabilidad_financiera(self):
        if (self.fondos_propios) > 0:
            return float(self.resultados_antes_impuestos) / float(self.fondos_propios)
        else:
            return 0

    def ratio_rentabilidad_inversion(self):
        if (self.pasivo_corriente + self.pasivo_no_corriente) > 0:
            return float(self.resultados_antes_impuestos) / float(self.pasivo_corriente + self.pasivo_no_corriente)
        else:
            return 0

    def ratio_resultados_sobre_ventas(self):
        if (self.importe_neto_cifra_negocio) > 0:
            return float(self.resultados_antes_impuestos) / float(self.importe_neto_cifra_negocio)
        else:
            return 0

    def __unicode__(self):
        return self.name

risk_cro/forms.py
from django import forms

class RatingForm(forms.Form):
	sector = forms.CharField()
	name = forms.CharField(max_length=255)
	antiguedad = forms.CharField(max_length=255)
	fondos_propios = forms.IntegerField()
	activo_corriente = forms.IntegerField()
	activo_no_corriente = forms.IntegerField()
	pasivo_corriente = forms.IntegerField()
	pasivo_no_corriente = forms.IntegerField()
	importe_neto_cifra_negocio = forms.IntegerField()
	gastos_financieros = forms.IntegerField()
	resultados_antes_impuestos = forms.IntegerField()

templates/risk_cro/cro_home.html
{% extends "app_base.html" %}
{% load static %}

{% block page_title %}
Risk Robo Advisor
{% endblock %}

{% block content %}
<img src="{% static 'images/lapices3.jpg' %}" id="bg" alt="">

	<div style="padding-top: 2rem;" class="grey-text text-darken-2">
		<div class="contents text-right">
			<div class="container">
          <h1 class="fadding light padding_cro_landing right-align">Zero line of defense</h1>
          <p class="fadding_2 light right-align" >Gestión de riesgos desde el cliente</p>
          <div class="row">
          	<div class="col m7 s12"></div>
	          	<div class="col m5 s12">
		          <a href="{% url 'risk_cro:search' %}" class="btn-large waves-effect waves-light transparent pad_top grey-text text-darken-3 border-grey">Clientes</a>
		          <a href="{% url 'risk_cro:credit_risk' %}" class="btn-large waves-effect waves-light transparent pad_top grey-text text-darken-3 border-grey">No clientes</a>
		        </div>
          </div>
          </div>
        </div>
	</div>
{% endblock %}

{% block alt_js %}
<script type="text/javascript">

	$(document).ready(function(){		
	});


</script>
{% endblock alt_js %}

templates/risk_cro/errors.html
{% if form.errors %}
    {% for field in form %}
        <p>{{field.name}}</p>
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/risk_cro/side-nav_cro.html
  {% load compress %}
  {% load static %}

  <ul id="slide-out" class="side-nav">
      <li>
        <div class="userView">
          <div class="background">
            <img src="{% static 'images/testimonial-bg.jpg' %}">
          </div>
          {% if company %}
          <a href="{% url 'risk_cro:detail' pk=company.pk %}"><img class="circle" src="{{ company.image }}"></a>
          <a href="{% url 'risk_cro:detail' pk=company.pk %}"><span class="white-text name">{{ company.name }}</span></a>
          <a href="{% url 'risk_cro:detail' pk=company.pk %}"><span class="white-text email">{{ company.email }}</span></a>
          <a href="{% url 'risk_cro:detail' pk=company.pk %}"><span class="white-text light email">Usuario: {{ request.user.get_full_name }}</span></a>
          {% endif %}
        </div>
      </li>
      <!-- <li class="">
        <li><span class="center-text tiny light"><small>{{ company.cnae }}</small></span></li>
      </li> -->
      <li><a href="{% url 'risk_cro:summary' %}"><i class="material-icons">view_quilt</i>Home</a></li>
      {% if company %}
      <li><a href="{% url 'risk_cro:detail' pk=company.pk %}"><i class="material-icons">airplay</i>Mi perfil</a></li>
      {% endif %}
      <!-- <li><a href="{% url 'empresas:faq' %}"><i class="material-icons">info_outline</i>FAQ & Comentarios</a></li> -->
      <li><div class="divider"></div></li>
      <li><a class="subheader">Análisis riesgos</a></li>
      <li><a href="{% url 'risk_cro:market_risk' %}"><i class="material-icons">assessment</i>Mercado!</a></li>
      <li><a href="{% url 'risk_cro:client_risk' %}"><i class="material-icons">assignment</i>Tus clientes!</a></li>
      <li><a href="{% url 'risk_cro:provider_risk' %}"><i class="material-icons">assignment</i>Tus proveedores!</a></li>
      <li><a href="{% url 'risk_cro:financial_risk' %}"><i class="material-icons">trending_down</i>Financiero!</a></li>
    
      <li><div class="divider"></div></li>
      <li><a class="subheader">Opciones</a></li>
      <!-- <li><a class="waves-effect" href="#">Ajustes<i class="material-icons">lock_open</i></a></li> -->
      <li><a class="waves-effect" href="/accounts/logout/">Salir<i class="material-icons">input</i></a></li>
    </ul>

templates/risk_cro/step1.html
						<div class="row">
				         	<div class="col m6 s12">
						      <div class="row">
						        <div class="input-field col m12">
						          <!-- <label for="company_name">Nombre de la compañía (opcional)</label> -->
						          {{ form.name.errors }}
						          <input id="id_name" name="name" type="text" maxlength="255" class="validate" required>
								  <label for="{{ form.name.id_for_label }}">Nombre de la compañía (opcional)</label>
								  <!-- {{ form.name }} -->
						        </div>
						      </div>
						      <div class="row">
						        <div class="input-field col m12">
						        {{ form.antiguedad.errors }}
						          <input id="id_antiguedad" name="antiguedad" type="number" class="validate" required>
						          <label for="{{ form.antiguedad.id_for_label }}">Antigüedad de tu empresa</label>
						        </div>
						      </div>
						      <div class="row">
						        <div class="input-field col m12">
						        {{ form.sector.errors }}
						          	<select id="id_sector" name="sector" class="validate" required>
								      	<option value="" disabled selected>Elije el sector de tu empresa</option>
								      	<option value="Agricultura">Agricultura</option>
								        <option value="Ganaderia y Pesca">Ganaderia y Pesca</option>
								        <option value="Energia">Energia</option>
								        <option value="Construcción (no promoción)">Construcción (no promoción)</option>
								        <option value="Promocción Inmobiliaria">Promocción Inmobiliaria</option>
								        <option value="Metalurgia y Maquinaria">Metalurgia y Maquinaria</option>
								        <option value="Fabricación Vehiculos a motor">Fabricación Vehiculos a motor</option>
								        <option value="Química">Química</option>
								        <option value="Mat.Construc. Y Transf. Pdtos Minerales">Mat.Construc. Y Transf. Pdtos Minerales</option>
								        <option value="Alimentación">Alimentación</option>
								        <option value="Textil y Confección">Textil y Confección</option>
								        <option value="Cuero, Piel y calzado">Cuero, Piel y calzado</option>
								        <option value="Otras Manufacturas">Otras Manufacturas</option>
								        <option value="Cio. Por mayor pdtos. Industriales">Cio. Por mayor pdtos. Industriales</option>
								        <option value="Cio. Por mayor pdtos consumo y manufacturas">Cio. Por mayor pdtos consumo y manufacturas</option>
								        <option value="Cio. Por menor">Cio. Por menor</option>
								        <option value="Transporte y Comunicaciones">Transporte y Comunicaciones</option>
								        <option value="Hosteleria, Turismo y Ocio">Hosteleria, Turismo y Ocio</option>
								        <option value="Servicios a empresas">Servicios a empresas</option>
								        <option value="Alquileres">Alquileres</option>
								        <option value="Otros Servicios">Otros Servicios</option>
								    </select>
								    <label for="{{ form.sector.id_for_label }}">¿A qué sector pertenence?</label>
						        </div>
						      </div>
						    </div>
						    <div class="col m6 s12">
						    	<h6 class="">Completando el formulario podràs conocer...</h6 class="flow-text">
						    	<ul class="collapsible popout" data-collapsible="accordion">
								    <li>
								      <div class="collapsible-header"><i class="material-icons">payment</i>Calcular tu capacidad de financiación.</div>
								      <div class="collapsible-body"><p>Rellena un sencillo formulario con datos básicos sobre tu empresa y averigua cuál es la capacidad de financiación de tu empresa.</p></div>
								    </li>
								    <li>
								      <div class="collapsible-header"><i class="material-icons">trending_down</i>Conocer tus puntos fuertes y débiles</div>
								      <div class="collapsible-body"><p>Descubre en qué puntos debes mejorar y obtén consejos sobre cómo aumentar la capacidad de financiación de tu empresa.</p></div>
								    </li>
								    <li>
								      <div class="collapsible-header"><i class="material-icons">supervisor_account</i>Comparar tu empresa con el sector.</div>
								      <div class="collapsible-body"><p>Podrás comparar la evolución de los ratios de tu empresa con la media de tu sector y descargarte el informe completo en pdf.</p></div>
								    </li>
								  </ul>
						    </div>
						  </div>
				         <div class="step-actions">
				            <button class="waves-effect waves-dark btn next-step">CONTINUAR</button>
				         </div>

templates/risk_cro/step3.html
						<div class="row">
				         	<div class="col m6 s12">
						      <div class="row">
						        <div class="input-field col m12">
						        	{{ form.fondos_propios.errors }}
						          <input id="id_fondos_propios" name="fondos_propios" type="number" class="validate" required>
								  <label for="{{ form.fondos_propios.id_for_label }}">Fondos propios</label>
						        </div>
						      </div>
						      <div class="row">
						        <div class="input-field col m12">
						        	{{ form.pasivo_corriente.errors }}
						          <input id="id_pasivo_corriente" name="pasivo_corriente" type="number" class="validate" required>
								  <label for="{{ form.pasivo_corriente.id_for_label }}">Pasivo corriente</label>
						        </div>
						      </div>
						      <div class="row">
						        <div class="input-field col m12">
						        {{ form.pasivo_no_corriente.errors }}
						          <input id="id_pasivo_no_corriente" name="pasivo_no_corriente" type="number" class="validate" required>
								  <label for="{{ form.pasivo_no_corriente.id_for_label }}">Pasivo no corriente</label>
						        </div>
						      </div>
						    </div>
						    <div class="col m6 s12">
						    	<h6 class="">El scoring es una combinación de los siguientes factores...</h6 class="flow-text">
						    	<canvas id="myChart2" width="200" height="190"></canvas>
						    </div>
						  </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.bundle.min.js"></script>

<script type="text/javascript">
	var config = {
		type: 'bar',
	    data: {

	        labels: ["Recursos/ventas", "Deuda/EBITDA", "Patrimonio/balance", "Deuda/activo", "Scoring"],
	        datasets: [{
	        	type: 'bar',
	            label: "Tu score",
	            backgroundColor: ["rgba(30,99,132,0.2)","rgba(30,99,132,0.2)","rgba(30,99,132,0.2)","rgba(30,99,132,0.2)","rgba(20,200,20,0.2)"],
	            borderColor: ["rgba(30,99,132,1)","rgba(30,99,132,1)","rgba(30,99,132,1)","rgba(30,99,132,1)","rgba(20,200,20,1)"],
	            hoverBackgroundColor: ["rgba(30,99,132,0.5)","rgba(30,99,132,0.5)","rgba(30,99,132,0.5)","rgba(30,99,132,0.5)","rgba(20,200,20,0.5)"],
	            hoverBorderColor: ["rgba(30,99,132,1)","rgba(30,99,132,1)","rgba(30,99,132,1)","rgba(30,99,132,1)","rgba(20,200,20,1)"],
	            data: [65, 59, 90, 81, 56],
	        }, {
	        	type: 'line',
	            label: "Media del sector",
	            backgroundColor: "rgba(54,162,235,0.2)",
	            borderColor: "rgba(54,162,235,1)",
	            hoverBackgroundColor: "rgba(54,162,235,0.5)",
	            hoverBorderColor: "rgba(54,162,235,1)",
	            data: [28, 19, 96, 27]
	        }]
	    }
	};

	var ctx = document.getElementById("myChart2").getContext("2d");
	new Chart(ctx, config);
</script>