LCX/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (HomeView,
					SegmentosView)

urlpatterns = [
    url(r'^$', HomeView, name='home'),
    url(r'^segmentos/$', SegmentosView, name='segmentos'),
]

empresas/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView

from .views import (HomeView, 
                    EmpresaDetailView,
                    InformeView,
                    DebugView,
                    # DataGenerator, 
                    Filling__eeffView,
                    ClientView, 
                    TransferListView, 
                    TransferDetailView, 
                    TrasferCreateView, 
                    CommercialClientsRecommendationsView2,
                    CommercialProvidersRecommendationsView2,
                    CommercialClientsRecommendationsView,
                    CommercialProvidersRecommendationsView,
                    FinancialRiskRecommendationsView,
                    ClientRiskRecommendationsView,
                    ProviderRiskRecommendationsView,
                    ProviderView,
                    EmpresasCreate,
                    ProductosCreate,
                    EstadosCreate,
                    CirbeCreate,
                    TranfersCreate,
                    ContentBasedCreate,
                    RecommendationsCreate,
                    OpportunityClientsView,
                    OpportunityProviderView,
                    FAQView,
                    SearchView,
                    IntroView,
                    SwitchView,
                    SummaryView,
                    get_data_mekko,
                    FinancialRiskRecommendationsView2,
                    MarketRiskRecommendationsView)

urlpatterns = [
    
    
    url(r'^intro/$', IntroView, name='empresas_intro'),
    url(r'^summary/$', SummaryView, name='summary'),
    url(r'^recommendations/clients$', CommercialClientsRecommendationsView2, name='recommendations_clients2'),
    url(r'^recommendations/providers$', CommercialProvidersRecommendationsView2, name='recommendations_providers2'),
    url(r'^recommendations/financial$', FinancialRiskRecommendationsView2, name='recommendations_financial2'),
    url(r'^get_data_mekko/$', get_data_mekko, name='get_data_mekko'),
    url(r'^$', HomeView, name='empresas_home'),
    #url(r'^create/$', EmpresaDetailView, name='empresa_create'),
    url(r'^(?P<pk>\d+)/$', EmpresaDetailView, name='detail'),
    url(r'^(?P<pk>\d+)/switch/$', SwitchView, name='switch'),
    url(r'^empresas/client_opportunities/$', OpportunityClientsView, name='client_opportunities'),
    url(r'^empresas/provider_opportunities/$', OpportunityProviderView, name='provider_opportunities'),
    #url(r'^update/$', EmpresaDetailView, name='empresa_update'),
    #url(r'^delete/$', EmpresaDetailView, name='empresa_delete'),
    # url(r'^empresa/(?P<empresa_id>[0-9]+)/transfer_create/$', TrasferCreateView, name='transfer_create'),
    url(r'^faq/$', FAQView, name='faq'),
    
    url(r'^debug_recomendaciones/$', DebugView, name='debug'),
    url(r'^recomendaciones/$', InformeView, name='informe'),
    url(r'^search/$', SearchView, name='search'),
    url(r'^clients/$', ClientView, name='clients'),
    url(r'^providers/$', ProviderView, name='providers'),
    url(r'^recommendations/$', CommercialClientsRecommendationsView, name='recommendations'),
    url(r'^recommendations/providers/$', CommercialProvidersRecommendationsView, name='recommendations_providers'),
    url(r'^recommendations/risk/financial$', FinancialRiskRecommendationsView, name='recommendations_financial_risk'),
    url(r'^recommendations/risk/client$', ClientRiskRecommendationsView, name='recommendations_client_risk'),
    url(r'^recommendations/risk/market$', MarketRiskRecommendationsView, name='risk_market'),
    url(r'^recommendations/risk/provider$', ProviderRiskRecommendationsView, name='recommendations_provider_risk'),
    url(r'^transfers/$', TransferListView, name='transfer_list'),
    url(r'^transfers/(?P<transfer_id>[0-9]+)/$', TransferDetailView, name='transfer_detail'),

    url(r'^generatedata/$', TemplateView.as_view(template_name="empresas/dataset_generator.html"), name='generate_empreses'),
    url(r'^generatedata/empresas/$', EmpresasCreate, name='empresas_create'),
    url(r'^generatedata/content_based/$', ContentBasedCreate, name='content_based_create'),
    url(r'^generatedata/productos/$', ProductosCreate, name='productos_create'),
    url(r'^generatedata/estados/$', EstadosCreate, name='estados_create'),
    url(r'^generatedata/transfers/$', TranfersCreate, name='transfers_create'),
    url(r'^generatedata/recommendations/$', RecommendationsCreate, name='recommedations_create'),
    url(r'^generatedata/cirbe/$', CirbeCreate, name='cirbe_create'),
    url(r'^generatedata/eeff_fill/$', Filling__eeffView, name='cirbe_create'),
    
]

marketplace/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from empresas import views
from risk_cro import views
from business.views import LandingView, AppsView, TestView
from allauth.account.views import LoginView, SignupView

urlpatterns = [
    url(r'^$', LandingView.as_view(), name='landing'), #views.home
    url(r'^admin/', admin.site.urls),
    url(r'^test/$', TestView),
    url(r'^pillstore/', AppsView.as_view(), name='home'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^empresas/', include('empresas.urls', namespace='empresas')),
    url(r'^cro/', include('risk_cro.urls', namespace='risk_cro')),
    url(r'^recommender/', include('recommender.urls', namespace='recommender')),
    url(r'^lcx/', include('LCX.urls', namespace='lcx')),
    url(r'^bidloan/', include('bidloan.urls', namespace='bidloan')),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

risk_cro/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (HomeView,
					CreditRaterView,
					RaterView,
                    EmpresaDetailView,
                    SearchView,
                    SummaryView,
                    MarketRiskRecommendationsView,
                    CommercialClientsRecommendationsView,
                    CommercialProvidersRecommendationsView,
                    FinancialRiskRecommendationsView)

urlpatterns = [
    url(r'^$', HomeView, name='cro_home'),
    url(r'^search/$', SearchView, name='search'),
    url(r'^summary/$', SummaryView, name='summary'),
    url(r'^(?P<pk>\d+)/$', EmpresaDetailView, name='detail'),
    url(r'^creditrater/$', CreditRaterView, name='credit_risk'),
    url(r'^rating/$', RaterView, name='rater'),
    url(r'^market_risk/$', MarketRiskRecommendationsView, name='market_risk'),
    url(r'^client_risk/$', CommercialClientsRecommendationsView, name='client_risk'),
    url(r'^provider_risk/$', CommercialProvidersRecommendationsView, name='provider_risk'),
    url(r'^financial_risk/$', FinancialRiskRecommendationsView, name='financial_risk'),
    
]

templates/app_base.html
{% load compress %}
{% load static %}
{% load mathfilters %}

<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <link rel="icon" href="{% static 'images/C--fakepath-pillango_logo.png' %}" type="image/png">
  <meta charset="utf-8">
  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>{% block page_title %}{{ _("Your Site") }}{% endblock %}</title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  {% block meta %}{% endblock %}

  {# use the CDN to get bootstrap css. can not be inside compress css block #}
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
  {% block cdn_css %}{% endblock cdn_css %}
  <link rel="stylesheet" href="{% static 'css/materialize-stepper.min.css' %}">
  
  {% compress css %}
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  
  {% block css %}{% endblock %}
  {% endcompress %}

  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->
  <!-- All JavaScript at the bottom, except this Modernizr build. -->
  {% compress js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
  {% endcompress %}
</head>

<body class="{% block body_class %}{% endblock %}" {% block body_attributes %}{% endblock %}>
  {% block body %}
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
  <![endif]-->
  <header>
    {% load i18n %}
  </header>

    {% if messages %}
        {% for message in messages %}
            <div class="chip {% if message.tags %}{{ message.tags }}{% endif %}" style="position: fixed; z-index: 10000; top: {{40|mul:forloop.counter}}px; left: 40px;">
              {{message}}
              <i class="close material-icons">close</i>
           </div>
        {% endfor %}
    {% endif %}
  <!-- {% include "messages_display.html" %} -->

  <div role="main">
        {% block content %}{% endblock %}
  </div>

  {% block side-nav %}{% endblock %}
  

  {% if buttons != False %}
      {% if menu != False %}
       <a href="#" data-activates="slide-out" class="button-collapse show-on-medium top-left" {% block hide %}{% endblock hide %}><i class="material-icons medium white-text">menu</i> <small class="white-text"> Beta 0.3</small></a>
      {% endif %}
      {% if power != False %}
            <a label="Exit" href={% if 1 == 0 %} "{% url 'empresas:search' %}" {% else %} "/accounts/logout/" {% endif %} class="show-on-medium positioning" {% block hide_2 %}{% endblock hide_2 %}><i class="material-icons medium {% if power_but_black == True %} grey-text {% else %} white-text {% endif %} ">power_settings_new</i></a>
      {% endif %}
  {% endif %}

  <!-- JavaScript at the bottom for fast page loading -->
  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  {% block cdn_js %}
  <script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>
  <script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/libs/jquery-2.1.1.min.js"><\/script>')</script>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
  <!-- jQueryValidation Plugin (optional) -->
  <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.min.js"></script>
  <!-- <script src="https://d3js.org/d3.v4.min.js"></script> -->
  {% endblock cdn_js %}

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>
  <!-- scripts concatenated and minified via django-compressor -->
  {% compress js %}
  {% block js %}
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/init.js' %}"></script>
  {% endblock js %}

  {% block alt_js %}
  {% endblock alt_js %}

  {% endcompress %}
  <!-- end scripts -->

  <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
       mathiasbynens.be/notes/async-analytics-snippet -->
  <script type="text/javascript">
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>
{% endblock %}
</body>
</html>

templates/base.html
{% load compress %}
{% load static %}
{% load mathfilters %}

<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <link rel="icon" href="{% static 'images/C--fakepath-pillango_logo.png' %}" type="image/png">
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>{% block page_title %}{{ _("Pillango") }}{% endblock %}</title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  {% block meta %}{% endblock %}

  {# use the CDN to get bootstrap css. can not be inside compress css block #}
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
  {% block cdn_css %}

  {% endblock cdn_css %}

  {% compress css %}
  <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link href="{% static 'css/style.css'  %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  {% block css %}{% endblock %}
  {% endcompress %}

  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build.
       Modernizr enables HTML5 elements & feature detects for optimal performance.
       Create your own custom Modernizr build: www.modernizr.com/download/ -->
  {% compress js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
  {% endcompress %}
</head>


<body class="{% block body_class %}{% endblock %}" {% block body_attributes %}{% endblock %}>
{% block body %}
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
  <![endif]-->
  <header>
    {% load i18n %}
  </header>

  {% include "navbar.html" %}

    {% if messages %}
        {% for message in messages %}
            <div class="chip {% if message.tags %}{{ message.tags }}{% endif %}" style="position: fixed; z-index: 10000; top: {{40|mul:forloop.counter}}px; left: 40px;">
              {{message}}
              <i class="close material-icons">close</i>
           </div>
        {% endfor %}
    {% endif %}

  <!-- {% include "messages_display.html" %} -->

  <div role="main">
    <div class="wrapper">

        {% block content %}{% endblock %}

    </div>
  </div>

  {% include "footer.html" %}


  <!-- JavaScript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  {% block cdn_js %}
  <script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>
  <script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/jquery-2.2.4.min.js"><\/script>')</script>
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>

  {% endblock cdn_js %}
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>
  <!-- scripts concatenated and minified via django-compressor -->
  {% compress js %}
  {% block js %}
    <script src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/materialize.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/init.js' %}"></script>

  {% endblock js %}
  {% endcompress %}
  <!-- end scripts -->

  <!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID.
       mathiasbynens.be/notes/async-analytics-snippet -->
  <script type="text/javascript">
    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>
{% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
Our Pillstore
{% endblock %}

{% block body_class %}
background_grey
{% endblock %}

{% block content %}
	
	<div id="home-banner" class="parallax-container padding_landing height_pillstore" style="height: 20rem !important;">
    <div class="section no-pad-bot">
      <div class="container">
            <h1 class="header center light grey-text text-darken-4 no-margin-top">Welcome to Pillango</h1>
            <h1 class="header center light grey-text text-darken-4">Showroom</h1>
            <div class="row center">
              <h6 class="header light grey-text text-darken-2">Take a look to our app demos</h6>
        	</div>
      </div>
    </div>
    <div class="parallax">
        <img src="{% static 'images/pills_apples3.jpg' %}" id="total" alt="Unsplashed background img 1">
    </div>
  </div>


    <div class="container">
	<h2 class="header center light_pers"></h2>
	<h5 class="header center light_pers"></h5>

	<div class="row">
		<div class="col s12 m4">
		<div class="card blue-grey lighten-1 hoverable">
			<div class="ribbon-wrapper-green"><div class="ribbon-green">NEW</div></div>
		    <div class="card-image waves-effect waves-block waves-light">
		      <img class="activator" src="{% static 'images/grow-your-business.jpg' %}">
		    </div>
		    <div class="card-content">
		      <span class="card-title activator white-text text-darken-4">Zero line of defense<i class="material-icons right">more_vert</i></span>
		      <div class="card-action">	
		      	<a href="{% url 'empresas:search' %}">Go to the App</a>
		      </div>
		    </div>
		    <div class="card-reveal">
		      <span class="card-title grey-text text-darken-4">Da impulso a tus clientes<i class="material-icons right">close</i></span>
		      <p>Servicio que impulsa el crecimiento y control de riesgos de las PYMES desde la información agregada de sus entidades financieras y el análisis de sus interacciones comerciales</p>
		    </div>
		   </div>
		</div>

		<div class="col s12 m4">
		<div class="card blue-grey lighten-1 hoverable">
			<div class="ribbon-wrapper-green"><div class="ribbon-green">NEW</div></div>
		    <div class="card-image waves-effect waves-block waves-light">
		      <img class="activator" src="{% static 'images/pencils.png' %}">
		    </div>
		    <div class="card-content">
		      <span class="card-title activator white-text text-darken-4">Risk Robo Advisor<i class="material-icons right">more_vert</i></span>
		      <div class="card-action">	
				<a href="{% url 'risk_cro:cro_home' %}">Go to the App</a>
			  </div>
		    </div>
		    <div class="card-reveal">
		      <span class="card-title grey-text text-darken-4">Plataforma Risk as a Service para las PYMES<i class="material-icons right">close</i></span>
		      <p>Servicio de medición del riesgo para las pymes. Éstas podrán valorar su exposición a los principales riesgo de su negocio y valorar sus necesidades y posibilidades de acceso a financiación.</p>
		    </div>
		</div>
		</div>

		<div class="col s12 m4">
		<div class="card blue-grey lighten-1 hoverable">
			<div class="ribbon-wrapper-green"><div class="ribbon-green">NEW</div></div>
		    <div class="card-image waves-effect waves-block waves-light">
		      <img class="activator" src="{% static 'images/pexels-photo-226460.jpeg' %}">
		    </div>
		    <div class="card-content">
		      <span class="card-title activator white-text text-darken-4">Marketplace B2B<i class="material-icons right">more_vert</i></span>
		      <div class="card-action">	
				<a href="{% url 'recommender:search' %}">Go to the App</a>
				</div>
		    </div>
		    <div class="card-reveal">
		      <span class="card-title grey-text text-darken-4">Encuentra tu socio perfecto<i class="material-icons right">close</i></span>
		      <p>Servicio de recomendación de clientes y proveedores  para las PYMES B2B. Reduce el tiempo (y los costes!) de tus esfuerzos comerciales con nuestro portal de contactos e impulsa tu negocio.</p>
		    </div>
		</div>
		</div>

	</div>

	<div class="row">
		<div class="col s12 m4">
		<div class="card blue-grey lighten-1 hoverable">
			<div class="ribbon-wrapper-green"><div class="ribbon-green">NOT YET</div></div>
		    <div class="card-image waves-effect waves-block waves-light">
		      <img class="activator" src="{% static 'images/fashion-men-vintage-colorful.jpg' %}">
		    </div>
		    <div class="card-content">
		      <span class="card-title activator white-text text-darken-4">Shopping go<i class="material-icons right">more_vert</i></span>
		      <div class="card-action">	
		      	<a href="">Go to the App</a>
		      </div>
		    </div>
		    <div class="card-reveal">
		      <span class="card-title grey-text text-darken-4">Los descuentos que te encuentran a ti<i class="material-icons right">close</i></span>
		      <p>Servicio de descuentos personalizados. Aprovechamos los patrones de consumo para identificar tus necesidades y ofrecerte los mejores descuentos. Caza las mejores oportunidades!</p>
		    </div>
		   </div>
		</div>

		<!-- <div class="col s12 m4">
		<div class="card blue-grey lighten-1 hoverable">
			<div class="ribbon-wrapper-green"><div class="ribbon-green">NOT YET</div></div>
		    <div class="card-image waves-effect waves-block waves-light">
		      <img class="activator" src="{% static 'images/risk.jpeg' %}">
		    </div>
		    <div class="card-content">
		      <span class="card-title activator white-text text-darken-4">BidLoan<i class="material-icons right">more_vert</i></span>
		      <div class="card-action">	
				<a href="">Go to the App</a>
			  </div>
		    </div>
		    <div class="card-reveal">
		      <span class="card-title grey-text text-darken-4">La financiación que te encuentra<i class="material-icons right">close</i></span>
		      <p>¿Por qué perder el tiempo en buscadores y comparadores de productos financieros? Describe tu necesidad y generamos una subasta entre las mejores entidades financieras para que puedas cumplir tus sueños (y pagar menos).</p>
		    </div>
		</div>
		</div> -->

	</div>

	</div>


{% endblock %}