LCX/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (HomeView,
					SegmentosView)

urlpatterns = [
    url(r'^$', HomeView, name='home'),
    url(r'^segmentos/$', SegmentosView, name='segmentos'),
]

empresas/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView

from .views import (HomeView, 
                    EmpresaDetailView,
                    InformeView,
                    DebugView,
                    # DataGenerator, 
                    Filling__eeffView,
                    ClientView, 
                    TransferListView, 
                    TransferDetailView, 
                    TrasferCreateView, 
                    CommercialClientsRecommendationsView2,
                    CommercialProvidersRecommendationsView2,
                    CommercialClientsRecommendationsView,
                    CommercialProvidersRecommendationsView,
                    FinancialRiskRecommendationsView,
                    ClientRiskRecommendationsView,
                    ProviderRiskRecommendationsView,
                    ProviderView,
                    EmpresasCreate,
                    ProductosCreate,
                    EstadosCreate,
                    CirbeCreate,
                    TranfersCreate,
                    ContentBasedCreate,
                    RecommendationsCreate,
                    OpportunityClientsView,
                    OpportunityProviderView,
                    FAQView,
                    SearchView,
                    IntroView,
                    SwitchView,
                    SummaryView,
                    get_data_mekko,
                    FinancialRiskRecommendationsView2,
                    MarketRiskRecommendationsView)

urlpatterns = [
    
    
    url(r'^intro/$', IntroView, name='empresas_intro'),
    url(r'^summary/$', SummaryView, name='summary'),
    url(r'^recommendations/clients$', CommercialClientsRecommendationsView2, name='recommendations_clients2'),
    url(r'^recommendations/providers$', CommercialProvidersRecommendationsView2, name='recommendations_providers2'),
    url(r'^recommendations/financial$', FinancialRiskRecommendationsView2, name='recommendations_financial2'),
    url(r'^get_data_mekko/$', get_data_mekko, name='get_data_mekko'),
    url(r'^$', HomeView, name='empresas_home'),
    #url(r'^create/$', EmpresaDetailView, name='empresa_create'),
    url(r'^(?P<pk>\d+)/$', EmpresaDetailView, name='detail'),
    url(r'^(?P<pk>\d+)/switch/$', SwitchView, name='switch'),
    url(r'^empresas/client_opportunities/$', OpportunityClientsView, name='client_opportunities'),
    url(r'^empresas/provider_opportunities/$', OpportunityProviderView, name='provider_opportunities'),
    #url(r'^update/$', EmpresaDetailView, name='empresa_update'),
    #url(r'^delete/$', EmpresaDetailView, name='empresa_delete'),
    # url(r'^empresa/(?P<empresa_id>[0-9]+)/transfer_create/$', TrasferCreateView, name='transfer_create'),
    url(r'^faq/$', FAQView, name='faq'),
    
    url(r'^debug_recomendaciones/$', DebugView, name='debug'),
    url(r'^recomendaciones/$', InformeView, name='informe'),
    url(r'^search/$', SearchView, name='search'),
    url(r'^clients/$', ClientView, name='clients'),
    url(r'^providers/$', ProviderView, name='providers'),
    url(r'^recommendations/$', CommercialClientsRecommendationsView, name='recommendations'),
    url(r'^recommendations/providers/$', CommercialProvidersRecommendationsView, name='recommendations_providers'),
    url(r'^recommendations/risk/financial$', FinancialRiskRecommendationsView, name='recommendations_financial_risk'),
    url(r'^recommendations/risk/client$', ClientRiskRecommendationsView, name='recommendations_client_risk'),
    url(r'^recommendations/risk/market$', MarketRiskRecommendationsView, name='risk_market'),
    url(r'^recommendations/risk/provider$', ProviderRiskRecommendationsView, name='recommendations_provider_risk'),
    url(r'^transfers/$', TransferListView, name='transfer_list'),
    url(r'^transfers/(?P<transfer_id>[0-9]+)/$', TransferDetailView, name='transfer_detail'),

    url(r'^generatedata/$', TemplateView.as_view(template_name="empresas/dataset_generator.html"), name='generate_empreses'),
    url(r'^generatedata/empresas/$', EmpresasCreate, name='empresas_create'),
    url(r'^generatedata/content_based/$', ContentBasedCreate, name='content_based_create'),
    url(r'^generatedata/productos/$', ProductosCreate, name='productos_create'),
    url(r'^generatedata/estados/$', EstadosCreate, name='estados_create'),
    url(r'^generatedata/transfers/$', TranfersCreate, name='transfers_create'),
    url(r'^generatedata/recommendations/$', RecommendationsCreate, name='recommedations_create'),
    url(r'^generatedata/cirbe/$', CirbeCreate, name='cirbe_create'),
    url(r'^generatedata/eeff_fill/$', Filling__eeffView, name='cirbe_create'),
    
]

marketplace/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from empresas import views
from risk_cro import views
from business.views import LandingView, AppsView, TestView
from allauth.account.views import LoginView, SignupView

urlpatterns = [
    url(r'^$', LandingView.as_view(), name='landing'), #views.home
    url(r'^admin/', admin.site.urls),
    url(r'^test/$', TestView),
    url(r'^pillstore/', AppsView.as_view(), name='home'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^empresas/', include('empresas.urls', namespace='empresas')),
    url(r'^cro/', include('risk_cro.urls', namespace='risk_cro')),
    url(r'^recommender/', include('recommender.urls', namespace='recommender')),
    url(r'^lcx/', include('LCX.urls', namespace='lcx')),
    url(r'^bidloan/', include('bidloan.urls', namespace='bidloan')),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empresas/forms.py
from django.forms import ModelForm, Textarea, ModelChoiceField, MultipleChoiceField, Select
from empresas.models import Transfer, Empresa

class TransferForm(ModelForm):

	destination_reference = ModelChoiceField(
		queryset=None,
		empty_label=None,
		label = 'Please select'
	) 

	def __init__(self, *args, **kwargs):
		super(TransferForm, self).__init__(*args, **kwargs)
		self.fields['destination_reference'].queryset = Empresa.objects.all()

	class Meta:
		model = Transfer
		fields = ['concept', 'amount','balance','destination_reference']
		widgets = {
		     'concept': Textarea(attrs={'cols': 40, 'rows': 15}),
		}

empresas/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.http import HttpResponse, HttpResponseRedirect, HttpRequest, JsonResponse
from django.contrib import messages
from django.shortcuts import redirect
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import View
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.staticfiles.templatetags.staticfiles import static
import pandas as pd
from django.core.urlresolvers import reverse
from .models import Empresa, Transfer, EstadosFinancieros, Productos, CIRBE
from .permissions import *
import dateutil.parser
from .forms import TransferForm
import datetime
from django.utils import timezone
from random import randint
from faker import Factory
from .als_recommender import *
from .item_based import *
import numpy
import os
import json
import random
import posixpath
from django.db.models import Avg, Max, Min, Count, Sum, Q
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import Prefetch


def get_data_mekko(request, *args, **kwargs):
	data = dict([
		('agrup', 'Riesgo Negocio'),
		('data', [
			dict([
				('name','Riesgo Macro / Sectorial'),
				('value',5),
				('image', os.path.join(settings.STATIC_ROOT, 'images/Macroeconomico.jpg') ),
				('info', 'Analizamos la evolución macroeconómica y sectorial por ti. Te ayudamos a predecir posibles tendencias del mercado'),
				('fuertes', 'Tu crecimiento en facturación es superior al crecimiento macroeconómico/sectorial'),
				('mejorar', '<p></p>')])
			,
			dict([
				('name','Riesgo Competencia'),
				('value',15),
				('image', os.path.join(settings.STATIC_ROOT, 'images/Competencia.jpg') ),
				('info', 'Analizamos tu competencia por ti. Te ayudamos a visualizar las tendencias de tu competencia más directa'),
				('fuertes', 'Tu empresa muestra mejores resultados y evolución que tu competencia'),
				('mejorar', '<p>Tu competencia ha experimentado un crecimiento destacable en volumen de ventas en el útlimo ejercicio</p>')])
			,
			dict([
				('name','Riesgo Normativo'),
				('value',0),
				('image', os.path.join(settings.STATIC_ROOT, 'images/Competencia.jpg') ),
				('info', 'FER DESAPAREIXER'),
				('fuertes', 'Funcionalidad no disponible. Disculpa las molestias! Estamos trabajando para incluir este análisis y ofrecerte un mejor servicio'),
				('mejorar', 'Funcionalidad no disponible. Disculpa las molestias! Estamos trabajando para incluir este análisis y ofrecerte un mejor servicio')])
			])
		]), dict([
			('agrup', 'Riesgo Clientes'),
			('data', [
			dict([
				('name','Riesgo Demanda'),
				('value',10),
				('image', os.path.join(settings.STATIC_ROOT, 'images/demanda.jpg') ),
				('info', 'Analizamos tus clientes por ti. Te ayudamos a predecir posibles desviaciones en la demanda'),
				('fuertes', '<p>Tus clientes han crecido en el último año.</p><p>Tus clientes son parecidos en tamaño y resultados a los clientes de tu competencia.</p>'),
				('mejorar', '')])
			,
			dict([
				('name','Riesgo Fidelidad'),
				('value',20),
				('image', os.path.join(settings.STATIC_ROOT, 'images/Fidelidad.jpg') ),
				('info', 'Analizamos la fidelidad de tus clientes. Te ayudamos a medir el riesgo de fuga de tus clientes'),
				('fuertes', '<p>Tus clientes te son fieles, con relaciones duraderas y elevado índice de penetración</p>'),
				('mejorar', 'Tus clientes te tienen como proveedor principal, por lo que existe poco margen de crecimiento con ellos')])
			,
			dict([
				('name','Riesgo Solvencia'),
				('value',15),
				('image', os.path.join(settings.STATIC_ROOT, 'images/incumplimiento.jpg') ),
				('info', 'Analizamos la solvencia de tus clientes. Te ayudamos a medir el riesgo de impago de sus facturas'),
				('fuertes', '<p>Tus clientes tienen una solvencia en línea con la de los clientes de la competencia</p>'),
				('mejorar', '')])
			,
			dict([
				('name','Riesgo Concentración'),
				('value',20),
				('image', os.path.join(settings.STATIC_ROOT, 'images/concentration_clients.jpg') ),
				('info', 'Analizamos los riesgos de concentración de tus ventas. Te ayudamos a medir las necesidades de diversificación de tu negocio'),
				('fuertes', '<p>Buena diversificación en tus ventas, en un gran número de clientes</p>'),
				('mejorar', '<p>Baja diversificación de tus ventas, efectuadas en muy pocas provincias</p>')])
			])
		]), dict([
			('agrup', 'Riesgo Proveedores'),
			('data', [
			dict([
				('name','Riesgo Oferta'),
				('value',10),
				('image', os.path.join(settings.STATIC_ROOT, 'images/oferta.jpg') ),
				('info', 'Analizamos tus proveedores por ti. Te ayudamos a predecir posibles cambios en tus proveedores'),
				('fuertes', '<p>Tus proveedores son más fuertes y con mejores resultados que los proveedores de tu competencia</p>'),
				('mejorar', '<p>Tus proveedores han disminuido sus volúmenes de negocio en el último año</p>')])
			,
			dict([
				('name','Riesgo Solvencia'),
				('value',10),
				('image', os.path.join(settings.STATIC_ROOT, 'images/incumplimiento.jpg') ),
				('info', 'Analizamos la solvencia de tus proveedores. Te ayudamos a medir el riesgo de incumplimiento de sus obligaciones'),
				('fuertes', '<p>Tus proveedores tienen una solvencia en línea con la de los proveedores de la competencia</p>'),
				('mejorar', '<p>Tus proveedores han disminuido su volúmen de negocio en el último año</p>')])
			,
			dict([
				('name','Riesgo Concentración'),
				('value',10),
				('image', os.path.join(settings.STATIC_ROOT, 'images/concentration_providers.jpg') ),
				('info', 'Analizamos los riesgos de concentración de tus compras. Te ayudamos a medir las oportunidades de diversificación de proveedores'),
				('fuertes', '<p>Buena diversificación en tus compras, con un gran número de proveedores</p>'),
				('mejorar', '<p>Baja diversificación de tus compras, efectuadas en muy pocas provincias</p>')])
			])
		]), dict([
			('agrup', 'Riesgo Financiero'),
			('data', [
			dict([
				('name','Riesgo Acceso a inversión'),
				('value',5),
				('image', os.path.join(settings.STATIC_ROOT, 'images/acceso inversion.jpg') ),
				('info', 'Analizamos tu balance. Te ayudamos a entender como vemos tu solvencia para que puedas financiar tus inversiones a largo plazo'),
				('fuertes', '<p>Dispones de una buena salud financiera</p><p>Ratios de endeudadmiento globales sensiblemente inferiores a los de tu competencia</p>'),
				('mejorar', '<p></p>')])
			,
			dict([
				('name','Riesgo Acceso a circulante'),
				('value',10),
				('image', os.path.join(settings.STATIC_ROOT, 'images/acceso circulante.jpg') ),
				('info', 'Analizamos tu balance. Te ayudamos a entender como vemos tu solvencia para que puedas anticipar tu acceso financiación circulante en caso de imprevistos'),
				('fuertes', '<p>Dispones de una buena salud financiera</p><p>Ratios de endeudadmiento a corto plazo sensiblemente inferiores a los de tu competencia</p>'),
				('mejorar', '<p></p>')])
			,
			dict([
				('name','Riesgo Optimización del working capital'),
				('value',10),
				('image', os.path.join(settings.STATIC_ROOT, 'images/working capital.jpg') ),
				('info', 'Analizamos tus necesidades de working capital. Te ayudamos a optimizarlas y te ofrecemos soluciones de financiación'),
				('fuertes', '<p>Fluctuaciones en necesidades de working capital en línea con las de tu competencia</p>'),
				('mejorar', '<p></p>')])
			,
			dict([
				('name','Riesgo Divisa'),
				('value',5),
				('image', os.path.join(settings.STATIC_ROOT, 'images/divisa.jpg') ),
				('info', 'Analizamos tu exposición al mercado de divisas. Te ayudamos a medir y gestionar el riesgo asociado.'),
				('fuertes', '<p>Tienes poca exposición al mercado de divisas</p>'),
				('mejorar', '<p></p>')])
			,
			dict([
				('name','Riesgo Tipo de interés'),
				('value',5),
				('image', os.path.join(settings.STATIC_ROOT, 'images/riesog tipo interes.jpg') ),
				('info', 'Analizamos tu exposición al tipo de interés. Te ayudamos a medir y gestionar el riesgo asociado.'),
				('fuertes', '<p>Tienes poca exposición a los tipos de interés</p>'),
				('mejorar', '<p></p>')])
			])

		])
	return JsonResponse(data, safe=False)

def Filling__eeffView(request):
	empresas = Empresa.objects.all()
	empresas_con_eeff = Empresa.objects.annotate(eeff_count=Count('estados_financieros')).filter(eeff_count__gte=2)
	print(empresas_con_eeff.count())
	empresas_con_eeff = empresas_con_eeff.annotate(sum_ebitda=Sum('estados_financieros__ebitda')).exclude(sum_ebitda=0)
	empresas_con_eeff = empresas_con_eeff.annotate(sum_ventas=Sum('estados_financieros__ventas')).exclude(sum_ventas=0)
	empresas_con_eeff = empresas_con_eeff.annotate(sum_resultado_explotacion=Sum('estados_financieros__resultado_explotacion')).exclude(sum_resultado_explotacion=0)
	print(empresas_con_eeff.count())
	empresas_sin_eeff = Empresa.objects.all().exclude(id__in=empresas_con_eeff)

	print('---------------------------- CON -')
	print(empresas_con_eeff.count())
	print(empresas_con_eeff.filter(pk=7))
	print('---------------------------- SIN -')
	print(empresas_sin_eeff.count())
	print(empresas_sin_eeff.filter(pk=7))

	for i, empresa_sin in enumerate(empresas_sin_eeff):

		empresa_con = empresas_con_eeff[randint(0, empresas_con_eeff.count() - 1)]
		eeff_to_be_deleted = EstadosFinancieros.objects.filter(empresa=empresa_sin)
		eeff_to_be_deleted.delete()
		print('----------------------------------------------------------------------------------------------')
		print(str(i) + 'Empresa sin estados financieros: ' + str(empresa_sin) +', le ponemos los de: '+ str(empresa_con))
		print(empresa_con.estados_financieros.all())
		for i, eeff in enumerate(empresa_con.estados_financieros.all()):
			estados_financiero = EstadosFinancieros()
			try:
				estados_financiero.empresa = empresa_sin

templates/empresas/debug.html
<body>
	{% block content %}
	{% endblock %}
</body>

templates/empresas/empresas_home.html
{% extends "app_base.html" %}
{% load staticfiles %}

{% block page_title %}
Marketplace - Pillango
{% endblock %}

{% block side-nav %}{% include "side-nav.html" %}{% endblock %}

{% block content %}
	<div class="wrap_register2">
		<div class="contents text-right">
          <a href="{% url 'empresas:detail' pk=company.pk %}" class="">
          	<div class="row">
		      <div class="col s12 m12">
		        <div class="card" style="background: rgba(255, 255, 250, .7);">
		        <div class="card-content">
		          	<span class="flow-text">Haz una visita guiada...</span>
		          		<div class="card-panel" style="background: rgba(245, 245, 245, .9); margin: 0 0 0 0; padding: 0 0 0 0;">
			          	<div class="mdl-card mdl-shadow--2dp">

						      <div class="mdl-card__supporting-text">

						        <div class="mdl-stepper-horizontal-alternative">
						          
						          <div class="mdl-stepper-step active-step">
						            <a href="{% url 'empresas:detail' pk=company.pk %}">
						              <div class="mdl-stepper-circle"><span>1</span></div>
						              <div class="mdl-stepper-title">Mi empresa</div>
						              <div class="mdl-stepper-optional">Resumen de tus principales resultados e indicadores comparados con los de tu competencia</div>
						              <div class="mdl-stepper-bar-right"></div>
						            </a>
						          </div>
						          
						          <div class="mdl-stepper-step active-step">
						            <a href=""> <!-- {% url 'empresas:recommendations' %} -->
						              <div class="mdl-stepper-circle"><span>2</span></div>
						              <div class="mdl-stepper-title">Mis Clientes/Proveedores</div>
						              <div class="mdl-stepper-optional">Resumen de tus clientes y proveedores comparados con los clientes y proveedores de tu competencia</div>
						              <div class="mdl-stepper-bar-left"></div>
						              <div class="mdl-stepper-bar-right"></div>
						            </a>
						          </div>
						          <div class="mdl-stepper-step active-step">
						            <a href=""> <!-- {% url 'empresas:recommendations_financial_risk' %} -->
						              <div class="mdl-stepper-circle"><span>3</span></div>
						              <div class="mdl-stepper-title">Mis Riesgos</div>
						              <div class="mdl-stepper-optional">Conoce tus riesgos financieros, los de tus clientes y los de tus proveedores y compárate con tu competencia</div>
						              <div class="mdl-stepper-optional"></div>
						              <div class="mdl-stepper-bar-left"></div>
						              <div class="mdl-stepper-bar-right"></div>
						            </a>
						          </div>

						          <div class="mdl-stepper-step active-step">
						            <a href=""> <!-- {% url 'empresas:informe' %} -->
						              <div class="mdl-stepper-circle"><span>4</span></div>
						              <div class="mdl-stepper-title">Mi Informe</div>
						              <div class="mdl-stepper-optional">Te indicamos los puntos más importantes detectados y te generamos una lista de recomendaciones</div>
						              <div class="mdl-stepper-bar-left"></div>
						            </a>
						          </div>
						        </div>

						      </div>

						</div>
					</div>
		        </div>
		      </div>
		      </div>
          </a>
          
          	<div class="row">
		      <div class="col s12 m12">
		        <div class="card" style="background: rgba(255, 255, 250, .7);">
		        <div class="card-content">
		          	<span class="flow-text" style="color: #039be5; ">...o descúbrelo por ti mismo</span>

		          	<div class="row">
		          		<div class="col s12 m3">
		          			<a href="{% url 'empresas:clients' %}" class="">
		          			<div class="card-panel hoverable" style="background: rgba(245, 245, 245, .9); margin: .5rem 0 0rem 0;">
		          				<div class="center-align">
		          				<i class="fa fa-user fa-2x" aria-hidden="true"></i>
								  <strong><p class=" black-text center-align" style="padding: 0rem 1rem 0rem 1rem;">Nuevos clientes</p></strong>
								  <span style="font-size: 12px;" class="black-text light">Visita nuestro marketplace, descubre y contacta con potenciales nuevos clientes que te recomendamos</span>
								</div>
					        </div>
					        </a>
		          		</div>
		          		<div class="col s12 m3">
		          			<a href="{% url 'empresas:providers' %}" class="">
		          			<div class="card-panel hoverable" style="background: rgba(245, 245, 245, .9); margin: .5rem 0 0rem 0;">
		          				<div class="center-align">
		          				<i class="fa fa-truck fa-2x" aria-hidden="true"></i>
								  <strong><p class=" black-text center-align" style="padding: 0rem 1rem 0rem 1rem;">Nuevos proveedores</p></strong>
								  <span style="font-size: 12px;" class="black-text light">Visita nuestro marketplace, descubre y contacta con potenciales nuevos proveedores que te recomendamos</span>
								</div>
					        </div>
					        </a>
		          		</div>
		          		<div class="col s12 m3">
		          			<a href="{% url 'empresas:switch' pk=company.pk %}" class="">
		          			<div class="card-panel hoverable" style="background: rgba(245, 245, 245, .9); margin: .5rem 0 0rem 0;">
		          				<div class="center-align">
		          				<i class="fa fa-venus-mars fa-2x" aria-hidden="true"></i>
								  <strong><p class=" black-text center-align" style="padding: 0rem 1rem 0rem 1rem;">Commercial Advisory</p></strong>
								  <span style="font-size: 12px;" class="black-text light">Conoce mejor tu cartera de clientes y proveedores y cómparala con la de tu competencia</span>
								</div>
					        </div>
					        </a>
		          		</div>
		          		<div class="col s12 m3">
		          			<a href="{% url 'empresas:recommendations_financial_risk' %}" class="">
		          			<div class="card-panel hoverable" style="background: rgba(245, 245, 245, .9); margin: .5rem 0 0rem 0;">
		          				<div class="center-align">
		          				<i class="fa fa-line-chart fa-2x" aria-hidden="true"></i>
								  <strong><p class=" black-text center-align" style="padding: 0rem 1rem 0rem 1rem;">Risk Advisory</p></strong>
								  <span style="font-size: 12px;" class="black-text light">Mide tus principales riesgos y recibe nuestras recomendaciones de cómo puedes gestionarlos</span>
								</div>
					        </div>
					        </a>
		          		</div>
		          	</div>
		          	

			    </div>
		        </div>
		      </div>
		      </div>
        </div>
	</div>
{% endblock %}

{% block alt_js %}
<script type="text/javascript">

	// $(document).ready(function(){
	// 	$( "#risk" ).click(function(e) {
	// 	Materialize.toast('Still under construction... Coming soon!', 4000);
	// })
	// });


</script>
{% endblock alt_js %}

templates/empresas/side-nav.html
  {% load compress %}
  {% load static %}

  <ul id="slide-out" class="side-nav">
      <li>
        <div class="userView">
          <div class="background">
            <img src="{% static 'images/testimonial-bg.jpg' %}">
          </div>
          <a href="{{ company.get_absolute_url }}"><img class="circle" src="{{ company.image }}"></a>
          <a href="{{ company.get_absolute_url }}"><span class="white-text name">{{ company.name }}</span></a>
          <a href="{{ company.get_absolute_url }}"><span class="white-text email">{{ company.email }}</span></a>
          <a href="{{ company.get_absolute_url }}"><span class="white-text light email">Usuario: {{ request.user.get_full_name }}</span></a>
        </div>
      </li>
      <!-- <li class="">
        <li><span class="center-text tiny light"><small>{{ company.cnae }}</small></span></li>
      </li> -->
      <li><a href="{% url 'empresas:summary' %}"><i class="material-icons">view_quilt</i>Home</a></li>
      <li><a href="{% url 'empresas:detail' pk=company.pk %}"><i class="material-icons">airplay</i>Mi perfil</a></li>
      <li><a href="{% url 'empresas:faq' %}"><i class="material-icons">info_outline</i>FAQ & Comentarios</a></li>
      <li><div class="divider"></div></li>
      <li><a class="subheader">Marketplace</a></li>
      <li><a href="{% url 'empresas:clients' %}"><i class="material-icons">person_pin</i>Nuevos clientes!</a></li>
      <li><a href="{% url 'empresas:providers' %}"><i class="material-icons">settings_input_antenna</i>Nuevos proveedores!</a></li>
      <li><div class="divider"></div></li>
      <li><a class="subheader">Análisis riesgos</a></li>
      <li><a href="{% url 'empresas:risk_market' %}"><i class="material-icons">assessment</i>Mercado!</a></li>
      <li><a href="{% url 'empresas:recommendations_clients2' %}"><i class="material-icons">assignment</i>Tus clientes!</a></li>
      <li><a href="{% url 'empresas:recommendations_providers2' %}"><i class="material-icons">assignment</i>Tus proveedores!</a></li>
      <li><a href="{% url 'empresas:recommendations_financial2' %}"><i class="material-icons">trending_down</i>Financiero!</a></li>
      
      
      <li><div class="divider"></div></li>
      <li><a class="subheader">Seguimiento</a></li>
      <li><a href="{% url 'empresas:client_opportunities' %}"><i class="material-icons">person_pin</i>Clientes guardados</a></li>
      <li><a href="{% url 'empresas:provider_opportunities' %}"><i class="material-icons">settings_input_antenna</i>Proveedores guardados</a></li>
      <!-- <li><a href="{% url 'empresas:recommendations' %}"><i class="material-icons">assessment</i>Commercial monitoring</a></li>
      <li><a href="{% url 'empresas:recommendations_financial_risk' %}"><i class="material-icons">trending_down</i>Risk monitoring</a></li> -->
    
      <li><div class="divider"></div></li>
      <li><a class="subheader">Opciones</a></li>
      <li><a class="waves-effect" href="#!">Ajustes<i class="material-icons">lock_open</i></a></li>
      <li><a class="waves-effect" href="{% url 'empresas:search' %}">Salir<i class="material-icons">input</i></a></li>
    </ul>